warning: in the working copy of 'docs/ROADMAP.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'lib/main.dart', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'pubspec.lock', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'test/widget_test.dart', LF will be replaced by CRLF the next time Git touches it
[1mdiff --git a/docs/ROADMAP.md b/docs/ROADMAP.md[m
[1mindex 9a4d66c..ac72ca8 100644[m
[1m--- a/docs/ROADMAP.md[m
[1m+++ b/docs/ROADMAP.md[m
[36m@@ -20,10 +20,10 @@[m [mDoel: een professionele, goed gedocumenteerde basis neerzetten voordat er functi[m
 Doel: de gekozen technische bouwstenen daadwerkelijk inrichten, nog zonder productfunctionaliteit.[m
 [m
 - [ ] Basis feature-first mapstructuur opzetten in `lib/`.[m
[31m-- [ ] Riverpod als state management inrichten.[m
[31m-- [ ] GoRouter als navigatieoplossing inrichten.[m
[32m+[m[32m- [x] Riverpod als state management inrichten.[m
[32m+[m[32m- [x] GoRouter als navigatieoplossing inrichten.[m
 - [ ] Supabase-project koppelen (configuratie, geen datamodel nog).[m
[31m-- [ ] Basis theming en app-shell.[m
[32m+[m[32m- [x] Basis theming en app-shell.[m
 [m
 ## Fase 2 — MVP: de eerste 30 minuten[m
 [m
[1mdiff --git a/lib/main.dart b/lib/main.dart[m
[1mindex bb16b7c..13decf5 100644[m
[1m--- a/lib/main.dart[m
[1m+++ b/lib/main.dart[m
[36m@@ -1,38 +1,8 @@[m
 import 'package:flutter/material.dart';[m
[32m+[m[32mimport 'package:flutter_riverpod/flutter_riverpod.dart';[m
 [m
[31m-import 'core/showcase/design_system_showcase_page.dart';[m
[31m-import 'core/theme/design_tokens.dart';[m
[32m+[m[32mimport 'core/app/thirty_app.dart';[m
 [m
 void main() {[m
[31m-  runApp(const ThirtyApp());[m
[31m-}[m
[31m-[m
[31m-class ThirtyApp extends StatefulWidget {[m
[31m-  const ThirtyApp({super.key});[m
[31m-[m
[31m-  @override[m
[31m-  State<ThirtyApp> createState() => _ThirtyAppState();[m
[31m-}[m
[31m-[m
[31m-class _ThirtyAppState extends State<ThirtyApp> {[m
[31m-  ThemeMode _themeMode = ThemeMode.system;[m
[31m-[m
[31m-  void _setThemeMode(ThemeMode mode) {[m
[31m-    setState(() => _themeMode = mode);[m
[31m-  }[m
[31m-[m
[31m-  @override[m
[31m-  Widget build(BuildContext context) {[m
[31m-    return MaterialApp([m
[31m-      title: 'THIRTY',[m
[31m-      debugShowCheckedModeBanner: false,[m
[31m-      theme: AppTheme.light,[m
[31m-      darkTheme: AppTheme.dark,[m
[31m-      themeMode: _themeMode,[m
[31m-      home: DesignSystemShowcasePage([m
[31m-        themeMode: _themeMode,[m
[31m-        onThemeModeChanged: _setThemeMode,[m
[31m-      ),[m
[31m-    );[m
[31m-  }[m
[32m+[m[32m  runApp(const ProviderScope(child: ThirtyApp()));[m
 }[m
[1mdiff --git a/pubspec.lock b/pubspec.lock[m
[1mindex 582d01a..926df53 100644[m
[1m--- a/pubspec.lock[m
[1m+++ b/pubspec.lock[m
[36m@@ -1,6 +1,30 @@[m
 # Generated by pub[m
 # See https://dart.dev/tools/pub/glossary#lockfile[m
 packages:[m
[32m+[m[32m  _fe_analyzer_shared:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: _fe_analyzer_shared[m
[32m+[m[32m      sha256: a49d6cf99e8d8e7a8e93668d09ced0bbdb954d0b4fccc2f5f9241c6b87fad95c[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "99.0.0"[m
[32m+[m[32m  analyzer:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: analyzer[m
[32m+[m[32m      sha256: "663efa951fb8a45e06f491223a604c93820598f20e6a99c25617a1576065e8b7"[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "12.1.0"[m
[32m+[m[32m  args:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: args[m
[32m+[m[32m      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "2.7.0"[m
   async:[m
     dependency: transitive[m
     description:[m
[36m@@ -25,6 +49,14 @@[m [mpackages:[m
       url: "https://pub.dev"[m
     source: hosted[m
     version: "1.4.1"[m
[32m+[m[32m  cli_config:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: cli_config[m
[32m+[m[32m      sha256: ac20a183a07002b700f0c25e61b7ee46b23c309d76ab7b7640a028f18e4d99ec[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "0.2.0"[m
   clock:[m
     dependency: transitive[m
     description:[m
[36m@@ -41,6 +73,30 @@[m [mpackages:[m
       url: "https://pub.dev"[m
     source: hosted[m
     version: "1.19.1"[m
[32m+[m[32m  convert:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: convert[m
[32m+[m[32m      sha256: b30acd5944035672bc15c6b7a8b47d773e41e2f17de064350988c5d02adb1c68[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "3.1.2"[m
[32m+[m[32m  coverage:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: coverage[m
[32m+[m[32m      sha256: "956a3de0725ca232ad353565a8290d3357592bf4250f6f298a185e2d949c5d3d"[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "1.15.1"[m
[32m+[m[32m  crypto:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: crypto[m
[32m+[m[32m      sha256: c8ea0233063ba03258fbcf2ca4d6dadfefe14f02fab57702265467a19f27fadf[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "3.0.7"[m
   cupertino_icons:[m
     dependency: "direct main"[m
     description:[m
[36m@@ -57,6 +113,22 @@[m [mpackages:[m
       url: "https://pub.dev"[m
     source: hosted[m
     version: "1.3.3"[m
[32m+[m[32m  file:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: file[m
[32m+[m[32m      sha256: a3b4f84adafef897088c160faf7dfffb7696046cb13ae90b508c2cbc95d3b8d4[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "7.0.1"[m
[32m+[m[32m  fixnum:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: fixnum[m
[32m+[m[32m      sha256: b6dc7065e46c974bc7c5f143080a6764ec7a4be6da1285ececdc37be96de53be[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "1.1.1"[m
   flutter:[m
     dependency: "direct main"[m
     description: flutter[m
[36m@@ -70,11 +142,72 @@[m [mpackages:[m
       url: "https://pub.dev"[m
     source: hosted[m
     version: "6.0.0"[m
[32m+[m[32m  flutter_riverpod:[m
[32m+[m[32m    dependency: "direct main"[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: flutter_riverpod[m
[32m+[m[32m      sha256: "56e81e662e6e54e59b231da57e90ac0d06ac67d8e3f2273c129a37ae6282b40c"[m
[32m+[m[32m      url: "https://pub.dev"[m
[32m+[m[32m    source: hosted[m
[32m+[m[32m    version: "3.4.2"[m
   flutter_test:[m
     dependency: "direct dev"[m
     description: flutter[m
     source: sdk[m
     version: "0.0.0"[m
[32m+[m[32m  flutter_web_plugins:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description: flutter[m
[32m+[m[32m    source: sdk[m
[32m+[m[32m    version: "0.0.0"[m
[32m+[m[32m  frontend_server_client:[m
[32m+[m[32m    dependency: transitive[m
[32m+[m[32m    description:[m
[32m+[m[32m      name: frontend_server_client[m
[32m+[m[32m      sha256: f64a0333a82f30b0cca061bc3d143813a486dc086b574bfb233b7c1372427694[m
[32m+[m[32m      url: "https://pub.dev"[